### ISSUE TITLE
Change the opacity of Your Quotes/ Favourite quotes option on the ViewQuotes page

### ISSUE THREAD

**Issue by PratyayDhond** [PratyayDhond/BookQuotes#10]
The selected option, i.e. view quotes(view all quotes) or favourite quotes should have better visibility than the other. That is it should be clear that it is the one selected currently

**Comment by satyamrs00** [comment]
I can do this. Assign it to me

**Comment by PratyayDhond** [comment]
> I can do this. Assign it to me

@satyamrs00 Sorry man I just completed it. How about you try looking for some enhancements in my repo, while I will try to find more features to be fixed
