### ISSUE TITLE
Update Fonts on Search Quotes Page

### ISSUE THREAD

**Issue by PratyayDhond** [PratyayDhond/BookQuotes#12]
I need some fonts for this website, the fonts should be free to use and should not have licensing issue ( It would be good if the fonts are from Google Fonts).

On the search Quotes page, the fonts look out of the place. 
I do not want to change the fonts of the logo or the tag line, but I want to replace the font in the search bar and and the quotes tabs. I would like it if the fonts are attractive and suit the background.
![image](https://user-images.githubusercontent.com/80563848/193455379-525d528b-58e9-49bb-8fcc-18569048fae5.png)

**Comment by PratyayDhond** [comment]
@satyamrs00 [satyamrs00](https://github.com/satyamrs00) if you are up for this tell me so.

**Comment by satyamrs00** [comment]
yes, I would like to work on it
